
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ForSpringJPA
    username: postgres
    password: Tama@1998
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true


